name: Blog2Masto
on:
  push:
    paths:
      - '_posts/*.md'
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Identify Added Blog Post
      id: identify_added_blog_post
      run: |
        sha=${{ github.sha }}
        echo "$sha"

        post_file=$(git diff --name-only --diff-filter=A $sha)
        echo "$post_file"
        if [ -n "$post_file" ]; then
          new_post_file=$(echo "$post_file" | head -n 1)
          echo "$new_post_file"
  
          title=$(awk '/^title:/ {$1=""; sub(/^[ \t]+/, ""); print}' "$new_post_file" | tr -d '"')
          date=$(echo "$new_post_file" | grep -oP '\d{4}-\d{2}-\d{2}' | sed 's/-/\//g')
          tags=$(awk '/^tags:/ {for (i=2; i<=NF; i++) print "#" $i}' "$new_post_file" | tr -d '[,]' | tr '\n' ' ')

          base_url="${{ secrets.BLOG_URL }}"
          url=$(echo "$title" | tr '[:upper:]' '[:lower:]' | tr -d '[:punct:]' | sed -E 's/[[:space:]]+/-/g' | sed -E 's/^-//;s/-$//')
          post_url="$base_url/$date/$url"

          echo "post_title=$title" >> $GITHUB_ENV
          echo "post_title=$title"
          echo "post_url=$post_url" >> $GITHUB_ENV
          echo "post_tags=$tags" >> $GITHUB_ENV
          echo "post_tags=$tags"
        fi
    - name: Post to Mastodon
      id: mastodon
      if: env.post_title != '' && env.post_url != ''
      uses: cbrgm/mastodon-github-action@v2
      with:
        access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        url: ${{ secrets.MASTODON_URL }}
        message: |
          "${{ env.post_title }}"
          ${{ env.post_url }}

    - name: Debugging and fallback post to Mastodon
      id: mastodon_fallback
      if: env.post_title == '' || env.post_url == ''
      run: |
        echo "Variable ${{ env.post_title }} or ${{ env.post_url }} was not set."
        echo "Sending a general fallback post."
  
    - name: Fallback Post to Mastodon
      if: env.post_title == '' || env.post_url == ''
      uses: cbrgm/mastodon-github-action@v2
      with:
        access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        url: ${{ secrets.MASTODON_URL }}
        message: |
          "Neuer Blogpost zu unserem Schokodrucker:"
          "https://teachbits.de"

          ${{ env.post_tags }} #FediLZ
